"""Closed vocabularies from Foundation Contract v0.1."""

from enum import StrEnum


class SchemaVersion(StrEnum):
    V0_1_0 = "0.1.0"


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    ANALYZING = "ANALYZING"
    AWAITING_REVIEW = "AWAITING_REVIEW"
    READY_FOR_EXECUTION = "READY_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    VALIDATING = "VALIDATING"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class DocumentStatus(StrEnum):
    REGISTERED = "REGISTERED"
    PREFLIGHTING = "PREFLIGHTING"
    READY = "READY"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    STAGED = "STAGED"
    RELEASED = "RELEASED"
    QUARANTINED = "QUARANTINED"


class DocumentPreflightStatus(StrEnum):
    PENDING = "PENDING"
    ASSESSING = "ASSESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class SourceAssessmentStatus(StrEnum):
    PENDING = "PENDING"
    ASSESSING = "ASSESSING"
    COMPLETED = "COMPLETED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class MappingProposalStatus(StrEnum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACCEPTED = "ACCEPTED"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ChangeProposalStatus(StrEnum):
    DRAFT = "DRAFT"
    BLOCKED = "BLOCKED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ApprovedChangeSetStatus(StrEnum):
    APPROVED = "APPROVED"
    INVALIDATED = "INVALIDATED"
    REVOKED = "REVOKED"
    SUPERSEDED = "SUPERSEDED"


class ExecutionStatus(StrEnum):
    QUEUED = "QUEUED"
    PREFLIGHTING = "PREFLIGHTING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    REFUSED = "REFUSED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ValidationStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"
    CANCELLED = "CANCELLED"


class ExceptionStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REMEDIATION_PENDING = "REMEDIATION_PENDING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class AnalysisStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class DocumentRole(StrEnum):
    TARGET = "TARGET"
    CURRENT_SOURCE = "CURRENT_SOURCE"
    HISTORICAL_SOURCE = "HISTORICAL_SOURCE"
    TEMPLATE = "TEMPLATE"
    EVALUATION_ONLY = "EVALUATION_ONLY"
    GENERATED_OUTPUT = "GENERATED_OUTPUT"


class DocumentFormat(StrEnum):
    DOCX = "DOCX"
    XLSX = "XLSX"
    PDF = "PDF"
    IMAGE = "IMAGE"


class ConformanceClass(StrEnum):
    TRANSITIONAL = "TRANSITIONAL"
    STRICT = "STRICT"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CapabilityStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PROTECTED = "PROTECTED"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"


class BindingStatus(StrEnum):
    PROPOSED = "PROPOSED"
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNSUPPORTED = "UNSUPPORTED"


class EvidenceStatus(StrEnum):
    UNASSESSED = "UNASSESSED"
    VERIFIED = "VERIFIED"
    INSUFFICIENT = "INSUFFICIENT"
    CONFLICTED = "CONFLICTED"
    STALE = "STALE"


class TargetVerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    BLOCKED = "BLOCKED"
    STALE = "STALE"


class CheckOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class FreshnessOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"


class ReviewOutcome(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    DEFER = "DEFER"
    REQUEST_MORE_SOURCE = "REQUEST_MORE_SOURCE"


class ActorType(StrEnum):
    HUMAN = "HUMAN"
    SYSTEM = "SYSTEM"
    AI = "AI"
    REPLAY_ENGINE = "REPLAY_ENGINE"
    VALIDATOR = "VALIDATOR"


class ReleaseStatus(StrEnum):
    WITHHELD = "WITHHELD"
    ELIGIBLE = "ELIGIBLE"
    RELEASED = "RELEASED"


class ChangeExecutionStatus(StrEnum):
    APPLIED = "APPLIED"
    REFUSED = "REFUSED"
    FAILED = "FAILED"
    NOT_ATTEMPTED = "NOT_ATTEMPTED"


class MutationOperation(StrEnum):
    REPLACE_RUN_TEXT = "REPLACE_RUN_TEXT"
    REPLACE_SDT_TEXT = "REPLACE_SDT_TEXT"
    REPLACE_SIMPLE_TABLE_CELL_TEXT = "REPLACE_SIMPLE_TABLE_CELL_TEXT"


class LocatorType(StrEnum):
    DOCX_CONTENT_CONTROL = "DOCX_CONTENT_CONTROL"
    DOCX_BOOKMARK = "DOCX_BOOKMARK"
    DOCX_PARAGRAPH = "DOCX_PARAGRAPH"
    DOCX_RUN = "DOCX_RUN"
    DOCX_TABLE_CELL = "DOCX_TABLE_CELL"
    DOCX_RELATIONSHIP = "DOCX_RELATIONSHIP"
    XLSX_CELL = "XLSX_CELL"
    XLSX_DEFINED_NAME = "XLSX_DEFINED_NAME"
    XLSX_TABLE_RANGE = "XLSX_TABLE_RANGE"


class EvidenceKind(StrEnum):
    NATIVE_VALUE = "NATIVE_VALUE"
    FORMULA_IDENTITY = "FORMULA_IDENTITY"
    SOURCE_EXCERPT = "SOURCE_EXCERPT"
    VALIDATION_OUTPUT = "VALIDATION_OUTPUT"


class SourceAuthority(StrEnum):
    AUTHORITATIVE = "AUTHORITATIVE"
    CONTEXT_ONLY = "CONTEXT_ONLY"
    UNDETERMINED = "UNDETERMINED"


class AssessmentMethod(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"


class RuleType(StrEnum):
    ALWAYS_UPDATE = "ALWAYS_UPDATE"
    UPDATE_IF_CHANGED = "UPDATE_IF_CHANGED"
    DERIVED_UPDATE = "DERIVED_UPDATE"
    CARRY_FORWARD = "CARRY_FORWARD"
    TEMPLATE_CONTROLLED = "TEMPLATE_CONTROLLED"
    PROTECTED = "PROTECTED"


class EvidenceCheckKind(StrEnum):
    SOURCE_PRESENCE = "SOURCE_PRESENCE"
    PERIOD = "PERIOD"
    FRESHNESS = "FRESHNESS"
    AUTHORITY = "AUTHORITY"
    COMPLETENESS = "COMPLETENESS"
    CONSISTENCY = "CONSISTENCY"
    VALUE_TYPE = "VALUE_TYPE"
    UNIT = "UNIT"
    FORMULA = "FORMULA"
    PROVENANCE = "PROVENANCE"


class ConditionValueTargetKind(StrEnum):
    INPUT_NATIVE_OBJECT = "INPUT_NATIVE_OBJECT"
    OUTPUT_APPROVED_CHANGE = "OUTPUT_APPROVED_CHANGE"


class ConditionKind(StrEnum):
    BINARY_HASH_EQUALS = "BINARY_HASH_EQUALS"
    TEXT_EQUALS = "TEXT_EQUALS"
    VALUE_EQUALS = "VALUE_EQUALS"
    CAPABILITY_SUPPORTED = "CAPABILITY_SUPPORTED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    PRESERVE_SCOPE = "PRESERVE_SCOPE"


class ValidationCheckKind(StrEnum):
    SCHEMA_PACKAGE = "SCHEMA_PACKAGE"
    PACKAGE_DIFF = "PACKAGE_DIFF"
    INTRA_PART_DIFF = "INTRA_PART_DIFF"
    PROTECTED_SCOPE = "PROTECTED_SCOPE"
    SEMANTIC_REPERCEPTION = "SEMANTIC_REPERCEPTION"
    BUSINESS_POSTCONDITION = "BUSINESS_POSTCONDITION"


class EventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    DOCUMENT_REGISTERED = "DOCUMENT_REGISTERED"
    DOCUMENT_PREFLIGHT_COMPLETED = "DOCUMENT_PREFLIGHT_COMPLETED"
    PERCEPTION_COMPLETED = "PERCEPTION_COMPLETED"
    PERCEPTION_FAILED = "PERCEPTION_FAILED"
    NATIVE_BINDING_ASSESSED = "NATIVE_BINDING_ASSESSED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    RULE_EVALUATED = "RULE_EVALUATED"
    SOURCE_ASSESSED = "SOURCE_ASSESSED"
    EVIDENCE_CHECKED = "EVIDENCE_CHECKED"
    EVIDENCE_ASSESSED = "EVIDENCE_ASSESSED"
    MAPPING_PROPOSED = "MAPPING_PROPOSED"
    AI_INTERACTION_RECORDED = "AI_INTERACTION_RECORDED"
    CHANGE_PROPOSED = "CHANGE_PROPOSED"
    REVIEW_DECIDED = "REVIEW_DECIDED"
    SOURCE_REQUESTED = "SOURCE_REQUESTED"
    DECISION_SUPERSEDED = "DECISION_SUPERSEDED"
    CHANGE_SET_APPROVED = "CHANGE_SET_APPROVED"
    APPROVAL_INVALIDATED = "APPROVAL_INVALIDATED"
    APPROVAL_REVOKED = "APPROVAL_REVOKED"
    REPLAY_REQUESTED = "REPLAY_REQUESTED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_REFUSED = "EXECUTION_REFUSED"
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    RELEASE_ELIGIBILITY_CONFIRMED = "RELEASE_ELIGIBILITY_CONFIRMED"
    RELEASE_WITHHELD = "RELEASE_WITHHELD"
    OUTPUT_QUARANTINED = "OUTPUT_QUARANTINED"
    OUTPUT_RELEASED = "OUTPUT_RELEASED"
    EXCEPTION_RECORDED = "EXCEPTION_RECORDED"
    EXCEPTION_RESOLVED = "EXCEPTION_RESOLVED"
    STATUS_TRANSITIONED = "STATUS_TRANSITIONED"


class AuditMetadataKind(StrEnum):
    GOVERNANCE = "GOVERNANCE"
    PERCEPTION = "PERCEPTION"
    NATIVE_BINDING = "NATIVE_BINDING"
    DETERMINISTIC_EVALUATION = "DETERMINISTIC_EVALUATION"
    AI_INTERACTION = "AI_INTERACTION"
    REPLAY = "REPLAY"
    VALIDATION = "VALIDATION"
    EXCEPTION = "EXCEPTION"


class ObjectType(StrEnum):
    FOUNDATION_TASK = "FoundationTask"
    DOCUMENT_ARTIFACT = "DocumentArtifact"
    DOCUMENT_VERSION = "DocumentVersion"
    DOCUMENT_PREFLIGHT_ASSESSMENT = "DocumentPreflightAssessment"
    PERCEPTION_SNAPSHOT = "PerceptionSnapshot"
    SEMANTIC_OBJECT = "SemanticObject"
    NATIVE_LOCATOR = "NativeLocator"
    NATIVE_BINDING = "NativeBinding"
    TARGET_CONTRACT_DEFINITION = "TargetContractDefinition"
    TARGET_REGION_DEFINITION = "TargetRegionDefinition"
    TARGET_CONTRACT_INSTANCE = "TargetContractInstance"
    TARGET_REGION = "TargetRegion"
    RULE_PACK = "RulePack"
    BUSINESS_RULE = "BusinessRule"
    RULE_EVALUATION = "RuleEvaluation"
    FRESHNESS_POLICY = "FreshnessPolicy"
    SOURCE_REQUIREMENT = "SourceRequirement"
    SOURCE_ASSESSMENT = "SourceAssessment"
    EVIDENCE_RECORD = "EvidenceRecord"
    EVIDENCE_CHECK = "EvidenceCheck"
    EVIDENCE_ASSESSMENT = "EvidenceAssessment"
    MAPPING_PROPOSAL = "MappingProposal"
    AI_INTERACTION_RECORD = "AIInteractionRecord"
    CHANGE_PROPOSAL = "ChangeProposal"
    REVIEW_DECISION = "ReviewDecision"
    APPROVED_CHANGE_SET = "ApprovedChangeSet"
    EXECUTION_RESULT = "ExecutionResult"
    CHANGE_EXECUTION_RESULT = "ChangeExecutionResult"
    VALIDATION_PLAN = "ValidationPlan"
    VALIDATION_REPORT = "ValidationReport"
    VALIDATION_CHECK_RESULT = "ValidationCheckResult"
    EXCEPTION_RECORD = "ExceptionRecord"
    ANALYSIS_RUN = "AnalysisRun"
    AUDIT_EVENT = "AuditEvent"


class SourceSufficiencyOutcome(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    MISSING = "MISSING"
    STALE = "STALE"
    CONFLICTING = "CONFLICTING"
    NOT_AUTHORITATIVE = "NOT_AUTHORITATIVE"
    AMBIGUOUS = "AMBIGUOUS"


class PeriodPolicy(StrEnum):
    CURRENT_PERIOD = "CURRENT_PERIOD"
    PRIOR_PERIOD = "PRIOR_PERIOD"
    SPECIFIC_PERIOD = "SPECIFIC_PERIOD"
    PERIOD_INDEPENDENT = "PERIOD_INDEPENDENT"


class EvidencePeriodScope(StrEnum):
    SPECIFIC_PERIOD = "SPECIFIC_PERIOD"
    PERIOD_INDEPENDENT = "PERIOD_INDEPENDENT"
    UNKNOWN = "UNKNOWN"


class DefinedNameScope(StrEnum):
    WORKBOOK = "WORKBOOK"
    WORKSHEET = "WORKSHEET"


class XlsxRangeKind(StrEnum):
    TABLE = "TABLE"
    RANGE = "RANGE"


class BusinessValueKind(StrEnum):
    TEXT = "TEXT"
    DECIMAL = "DECIMAL"
    INTEGER = "INTEGER"
    DATE = "DATE"
    BOOLEAN = "BOOLEAN"
    CURRENCY = "CURRENCY"
    PERCENT = "PERCENT"
    STRUCTURED = "STRUCTURED"


class MutationPayloadType(StrEnum):
    RUN_TEXT_REPLACEMENT = "RUN_TEXT_REPLACEMENT"
    SDT_TEXT_REPLACEMENT = "SDT_TEXT_REPLACEMENT"
    SIMPLE_TABLE_CELL_TEXT_REPLACEMENT = "SIMPLE_TABLE_CELL_TEXT_REPLACEMENT"


class ErrorCode(StrEnum):
    INVALID_CONTRACT = "INVALID_CONTRACT"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND"
    EVALUATOR_BINDING_UNAVAILABLE = "EVALUATOR_BINDING_UNAVAILABLE"
    EVALUATOR_CONFIGURATION_MISMATCH = "EVALUATOR_CONFIGURATION_MISMATCH"
    STALE_DOCUMENT_VERSION = "STALE_DOCUMENT_VERSION"
    LOCATOR_NOT_FOUND = "LOCATOR_NOT_FOUND"
    LOCATOR_AMBIGUOUS = "LOCATOR_AMBIGUOUS"
    LOCATOR_FINGERPRINT_MISMATCH = "LOCATOR_FINGERPRINT_MISMATCH"
    CAPABILITY_UNKNOWN = "CAPABILITY_UNKNOWN"
    UNSUPPORTED_NATIVE_OBJECT = "UNSUPPORTED_NATIVE_OBJECT"
    PROTECTED_OBJECT = "PROTECTED_OBJECT"
    EXECUTION_UNSUPPORTED = "EXECUTION_UNSUPPORTED"
    STRICT_OOXML_MUTATION_UNQUALIFIED = "STRICT_OOXML_MUTATION_UNQUALIFIED"
    SOURCE_MISSING = "SOURCE_MISSING"
    SOURCE_STALE = "SOURCE_STALE"
    SOURCE_NOT_AUTHORITATIVE = "SOURCE_NOT_AUTHORITATIVE"
    SOURCE_CONFLICTING = "SOURCE_CONFLICTING"
    SOURCE_AMBIGUOUS = "SOURCE_AMBIGUOUS"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    EVIDENCE_NOT_VERIFIED = "EVIDENCE_NOT_VERIFIED"
    AI_AUTHORITY_VIOLATION = "AI_AUTHORITY_VIOLATION"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_CONTENT_MISMATCH = "APPROVAL_CONTENT_MISMATCH"
    AUTHORIZATION_NOT_APPROVED = "AUTHORIZATION_NOT_APPROVED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    EXECUTION_CONFLICT = "EXECUTION_CONFLICT"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    REPLAY_ENGINE_FAILURE = "REPLAY_ENGINE_FAILURE"
    INDEPENDENT_VALIDATOR_NOT_QUALIFIED = "INDEPENDENT_VALIDATOR_NOT_QUALIFIED"
    VALIDATION_OBSERVATION_UNAVAILABLE = "VALIDATION_OBSERVATION_UNAVAILABLE"
    UNAUTHORIZED_CHANGE_DETECTED = "UNAUTHORIZED_CHANGE_DETECTED"
    PROTECTED_SCOPE_VIOLATION = "PROTECTED_SCOPE_VIOLATION"
    RELEASE_BLOCKED_INCOMPLETE_TARGETS = "RELEASE_BLOCKED_INCOMPLETE_TARGETS"
    EVENT_INTEGRITY_MISMATCH = "EVENT_INTEGRITY_MISMATCH"
    EVENT_CAUSATION_INVALID = "EVENT_CAUSATION_INVALID"
    UNSUPPORTED_FILE_FORMAT = "UNSUPPORTED_FILE_FORMAT"
    ENCRYPTED_DOCUMENT = "ENCRYPTED_DOCUMENT"
    CORRUPTED_DOCUMENT = "CORRUPTED_DOCUMENT"
    DOCUMENT_TOO_LARGE = "DOCUMENT_TOO_LARGE"
    MALWARE_DETECTED = "MALWARE_DETECTED"
    PREFLIGHT_FAILED = "PREFLIGHT_FAILED"
    PERCEPTION_FAILED = "PERCEPTION_FAILED"
    PERCEPTION_MISMATCH = "PERCEPTION_MISMATCH"
    SEMANTIC_OBJECT_NOT_FOUND = "SEMANTIC_OBJECT_NOT_FOUND"
    NATIVE_BINDING_MISSING = "NATIVE_BINDING_MISSING"
    MAPPING_AMBIGUOUS = "MAPPING_AMBIGUOUS"
    MAPPING_UNRESOLVED = "MAPPING_UNRESOLVED"
    AI_CONTEXT_INCOMPLETE = "AI_CONTEXT_INCOMPLETE"
    AI_OUTPUT_INVALID = "AI_OUTPUT_INVALID"
    AI_UNSUPPORTED_INFERENCE = "AI_UNSUPPORTED_INFERENCE"
    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    MUTATION_NOT_AUTHORIZED = "MUTATION_NOT_AUTHORIZED"
    POSTCONDITION_FAILED = "POSTCONDITION_FAILED"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    PACKAGE_DIFF_FAILED = "PACKAGE_DIFF_FAILED"
    INTRA_PART_DIFF_FAILED = "INTRA_PART_DIFF_FAILED"
    SEMANTIC_REPERCEPTION_FAILED = "SEMANTIC_REPERCEPTION_FAILED"
    BUSINESS_RECONCILIATION_FAILED = "BUSINESS_RECONCILIATION_FAILED"
